language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

addons:
  sonarqube:
    token:
      secure: tkB6wNf+dGu/paCLoE3CuBkLxMoZ08LG4dMjh+GvZcu3MenWnqk3FMcFlXYBuWdkTMmmfZG/LQ7k8fSl2fpChOtWHSb1LB1F8YxHb7rZBbPEMqQwZHtUBNOaUiIELcwQsQJEk+69Kyp2BPzFcVqW2vl55tmH0oys6Dd0MXQ/2mg8qC6xETd4evKYCzqCTIuE+3tAR3qis/hVSZdSAzylLAQuArvbgU9AN28udXVhGp5spw4XtQNgZTNMtPBBo95j70eheB6CzUFkVcu/jspC7cUZWK4Anxuo9gcv7TODPNOiGPBuNY2UB0kaGTDESrvXVt4bq3MxS2x8XEEeWx7xoswSMLTxCtlku5Jo5nMAmq0peaGZy1hBhaD3XR7dp25bonWktEhTKEMYF94R3sdLQAp3NTFQq/ZqKgI50MZrmO9P+JL5Sj7u/3QCT6v4OGWxbDE5aHKvBHRlH7qX0jvfn50RGyPAl5kH+jK1/zsKIgp9yz1Ig/zK98/WRjt7krrnZeuj7O8u+2B11ZlanJ5sBngFVp93XIQnuf05H7mc1Q8lg/T2a6y5c70yBTYn843uVcvi2UVenLMywkOcp0H0zLqlt3dUfFIVGVnoVhrYUwNW6Lhe7NORTPa7h8oYpqBIStxT61qoefGXy64gSCEIsgtk5EP13rBqvYJAYt4tvxU=

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success: ./release.sh
